In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# create a tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the dimensio of tensor using ndim
scalar.ndim

0

In [ ]:
# create a vector using tf.constant
vector = tf.constant([23,43,45])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([23, 43, 45], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# create a matrix more than one dimension
matrix = tf.constant([[10,5],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10,4,3],
                             [3,5,2],
                             [0,9,5]],dtype=tf.float16) # Here we are specifying datatype of tensor
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  4.,  3.],
       [ 3.,  5.,  2.],
       [ 0.,  9.,  5.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a tensor(multidimensional array)
tensor = tf.constant([[[10,3,5],
                       [9,5,4]],
                      [[5,6,3],
                      [4,0,6]],
                     [[1,2,3],
                     [8,4,3]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  3,  5],
        [ 9,  5,  4]],

       [[ 5,  6,  3],
        [ 4,  0,  6]],

       [[ 1,  2,  3],
        [ 8,  4,  3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# Tensor --> Tensor is a n dimensional array of numbers (where n can be any number 0,1,2,.... )

Let's Create tensor with `tf.variable`

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor =tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
changeable_tensor[0]=7
changeable_tensor  # This doesnot work out because assignment operator is not supported for tensor

TypeError: ignored

In [ ]:
# Lets try another method
changeable_tensor[0].assign(7)
changeable_tensor     # It works out and our tensor changed to [7,7]

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Lets try to change unchangeable_tensor
unchangeable_tensor[0]=7
unchangeable_tensor   # Assignment also does not workout for tf.constant

TypeError: ignored

In [ ]:
# Lets try assign() method
unchangeable_tensor.assign(7)
unchangeable_tensor   # It also throws error because this tensor can not be changed by any method that means tf.constant tensor immutable

### Create Random tensor using tensor flow

In [ ]:
# Create random tensor of normal distribution
rand_tensor1 = tf.random.Generator.from_seed(40)
rand_tensor1 = rand_tensor1.normal(shape=(3,2))
rand_tensor2 = tf.random.Generator.from_seed(40)
rand_tensor2=rand_tensor2.normal(shape=(3,2))
rand_tensor1,rand_tensor2,rand_tensor1==rand_tensor2  # 

In [ ]:
# Create random tensor of uniform distribution
rand_tensor3=tf.random.uniform(shape=(3,2))
rand_tensor3

### Shuffle tensor

In [ ]:
non_shuffled_tensor = tf.constant([[10,3,4],
                                   [5,3,2],
                                   [9,4,3]])
non_shuffled_tensor

In [ ]:
# Lets Shuffle this tensor
shuffled_tensor=tf.random.shuffle(non_shuffled_tensor,seed=40,name='shuffled_tensor') 
shuffled_tensor    #Here we set only operational seed so when it is run again and again it shuffled randomly

In [ ]:
# What if we want same shuffled tensor all the time
tf.random.set_seed(7)   # Setting global seed
shuffle_tensor = tf.random.shuffle(non_shuffled_tensor,seed=40,name='shuffled_tensor') 
shuffle_tensor  # Now it runs again and again you will find the same random tensor all the time.

In [ ]:
# Other ways of creating tensor
zeros_tensor=tf.zeros(shape=(3,4))
zeros_tensor

In [ ]:
# unit tensor
ones_tensor = tf.ones(shape=(4,5))
ones_tensor

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A = np.arange(1,25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Convert numpy array into tensor
tensor_A = tf.constant(numpy_A)
tensor_B = tf.constant(numpy_A,shape=(2,4,3))
tensor_A,tensor_B

(<tf.Tensor: shape=(24,), dtype=int64, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

In [ ]:
tensor_A.ndim,tensor_B.ndim

(1, 3)

### Getting information from tensors:
When dealing with tensor you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# create a 4 rank tensor (4-dimensional)
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# what is the rank of tensor
rank_4_tensor.ndim

4

In [ ]:
# What is the shape of the tensor
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
# What is the 0 dimensional element
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# What is the number of elements in tensor
print(tf.size(rank_4_tensor))
print(tf.size(rank_4_tensor).numpy())

tf.Tensor(120, shape=(), dtype=int32)
120


### Indexing Tensor:
Tensor can be indexed in the same way as python lists

In [ ]:
List = [1,2,4,5]
List

[1, 2, 4, 5]

In [ ]:
List[:2]

[1, 2]

In [ ]:
# Get the first two element of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension except the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get the last element form each dimension
rank_4_tensor[:,:,:,-1]

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
Rank2Tensor=tf.constant([[10,5,3],[9,43,90]])
Rank2Tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  5,  3],
       [ 9, 43, 90]], dtype=int32)>

In [ ]:
#Create Rank3 Tnesor
Rank3Tensor = Rank2Tensor[:,:,tf.newaxis]
Rank3Tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[10],
        [ 5],
        [ 3]],

       [[ 9],
        [43],
        [90]]], dtype=int32)>

In [ ]:
Rank3Tensor.ndim

3

In [ ]:
#Alternative to expand dimension of tensor
Rank3_Tensor = tf.expand_dims(Rank2Tensor,axis=-1) # It expands the last dimension
Rank3_Tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[10],
        [ 5],
        [ 3]],

       [[ 9],
        [43],
        [90]]], dtype=int32)>

In [ ]:
# Expand axis 0 dimension
Rank3_Tensor = tf.expand_dims(Rank2Tensor,axis=0)
Rank3_Tensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[10,  5,  3],
        [ 9, 43, 90]]], dtype=int32)>

#### Manipulation of tensor
**Basic Operatos** 

`+`,`-`,`*`,`/`

In [ ]:
Tensor = tf.constant([[10,4],
                      [90,54]])
Tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [90, 54]], dtype=int32)>

In [ ]:
newTensor=Tensor+10
newTensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 20,  14],
       [100,  64]], dtype=int32)>

In [ ]:
newTensor=Tensor-10
newTensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -6],
       [80, 44]], dtype=int32)>

In [ ]:
newTensor = Tensor*10
newTensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  40],
       [900, 540]], dtype=int32)>

In [ ]:
newTensor = Tensor/10
newTensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.4],
       [9. , 5.4]])>

In [ ]:
# We can also use tensorflow built-in function to carry out these operations
newTensor = tf.add(Tensor,10)

In [ ]:
newTensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 20,  14],
       [100,  64]], dtype=int32)>

In [ ]:
newTensor=tf.multiply(Tensor,10)

In [ ]:
newTensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  40],
       [900, 540]], dtype=int32)>

### Matrix Multiplication of tensors
**There are three methods to perform matrix multiplication in tensorflow**

`tf.matmul()`

`tf.tensordot()`

`@`

In [ ]:
X=tf.constant([[10,5,3],[2,3,5],[0,4,3]])
X

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  5,  3],
       [ 2,  3,  5],
       [ 0,  4,  3]], dtype=int32)>

In [ ]:
X.shape

TensorShape([3, 3])

In [ ]:
X.shape[1]

3

In [ ]:
Y = tf.constant([[10,5],[2,3],[0,4]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  5],
       [ 2,  3],
       [ 0,  4]], dtype=int32)>

In [ ]:
Y.shape

TensorShape([3, 2])

In [ ]:
Y.shape[0]

3

In [ ]:
# Perform matrix multiplication
Z=tf.matmul(X,Y)
Z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[110,  77],
       [ 26,  39],
       [  8,  24]], dtype=int32)>

In [ ]:
# Lets try `@` for matrix multiplication
Z=X@Y
Z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[110,  77],
       [ 26,  39],
       [  8,  24]], dtype=int32)>

In [ ]:
# Lets try tf.tensordot()
z=tf.tensordot(X,Y,axes=1)
z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[110,  77],
       [ 26,  39],
       [  8,  24]], dtype=int32)>

In [ ]:
y=tf.reshape(Y,[6,])


In [ ]:
y

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([10,  5,  2,  3,  0,  4], dtype=int32)>

In [ ]:
y=tf.reshape(Y,shape=(2,3))
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  5,  2],
       [ 3,  0,  4]], dtype=int32)>

In [ ]:
# Create transpose of matrix
y=tf.transpose(Y)
print("original matrix:\n",Y.numpy(),"\n The transpose matrix:\n",y.numpy())

original matrix:
 [[10  5]
 [ 2  3]
 [ 0  4]] 
 The transpose matrix:
 [[10  2  0]
 [ 5  3  4]]


### Playing with datatypes of tensor


In [ ]:
Tensor  # Notice it is dtype=int32

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [90, 54]], dtype=int32)>

In [ ]:
# Make the above tensor float 16
tensor=tf.cast(Tensor,dtype='float16')
tensor   # Notice that it is now float16 type

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  4.],
       [90., 54.]], dtype=float16)>

In [ ]:
Tensor   # hey! notice original tensor dtype has not changed

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [90, 54]], dtype=int32)>

### Aggregation of Tensor:
* Get the the minimum
* Get the maximum
* Get the mean
* Get the sum
* Get the stadardvariance
* Get the variance

In [ ]:
# Create a random tensor between 0 and 100 of 50 size
random_tensor = tf.constant(np.random.randint(0,100,50)) 
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([38, 51, 98, 56, 24, 73, 58, 66,  3, 18, 74, 69, 15, 80, 89, 34, 80,
       65, 18, 79, 71, 66, 33, 64,  2, 39, 91, 14, 57,  0, 18, 36,  3, 83,
       15, 49, 72, 23, 49, 67, 97, 74, 28, 74, 24, 68,  2,  7, 40, 47])>

In [ ]:
random_tensor.shape, random_tensor.ndim,tf.size(random_tensor)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [ ]:
# Find the minimum value in the tensor
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Find the maximum of the tensor
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the sum of all elements
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2401>

In [ ]:
# Find the mean of the tensor
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
# Findt the variance of the tensor
tf.reduce_variance(random_tensor)  # This doesnt work becuase it accepts only float dtype

AttributeError: ignored

In [ ]:
tf.reduce_variance(tf.cast(random_tensor,dtype='float32') # This also doesnot work because we have to also include math. see below cell

In [ ]:
# Find the variance of the tensor
tf.math.reduce_variance(tf.cast(random_tensor,dtype='float16'))

In [ ]:
tf.math.reduce_std(tf.cast(random_tensor,dtype='float32'))

In [ ]:
# There is also probability package in tensorflow we have to import that to perform statistics operations
import tensorflow_probability as tfp

In [ ]:
# Find variance
tfp.stats.variance(random_tensor)

In [ ]:
tfp.stats.stddev(random_tensor)  # check why it is throwing error

#### Find the positional gloabal maximum and minimum

In [ ]:
# create a random tenso
tensor = tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

In [ ]:
# Find the index of the maximum number from the tensor
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [ ]:
# check the maximum number using the index printed above
tensor[tf.argmax(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9869994>

In [ ]:
# Finde the max from tensor using reduc_max function
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9869994>

In [ ]:
# Find the index of minimum number from the tensor
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [ ]:
# Check the minimum number using the index printed above
tensor[tf.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.013772249>

In [ ]:
# Check the minimum number using reduce_min function
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.013772249>

#### Squeezing tensor 

In [ ]:
# Create a random tensor 
tf.random.set_seed(42)
tensor=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
# Squeeze the tensor
squeezed_tensor=tf.squeeze(tensor)

In [ ]:
squeezed_tensor # tf.squeeze remove removes dimensions of size 1 from the shape of a tensor.

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tensor.shape,squeezed_tensor.shape

(TensorShape([1, 1, 1, 1, 50]), TensorShape([50]))

#### One hot encoding

In [ ]:
# Create a tensor
A=tf.range(0,10)
A

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Perform one hot encoding on A
tf.one_hot(A,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# perform custom one hot encoding
tf.one_hot(A,depth=10,on_value="yes",off_value="no")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'yes', b'no', b'no', b'no', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'yes', b'no', b'no', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'yes', b'no', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'yes', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'yes', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'yes', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'yes', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'yes',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'no',
        b'yes']], dtype=object)>

#### Square,log and Squareroot of tensors

In [ ]:
G = tf.range(0,10,3)

In [ ]:
G

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 3, 6, 9], dtype=int32)>

In [ ]:
tf.square(G)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  9, 36, 81], dtype=int32)>

In [ ]:
tf.math.log(tf.cast(G,dtype=tf.float32)) # This requires math and also list should be non-int type

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([     -inf, 1.0986123, 1.7917595, 2.1972246], dtype=float32)>

In [ ]:
tf.sqrt(G) # it throws an error because it requies non-int type

InvalidArgumentError: ignored

In [ ]:
tf.sqrt(tf.cast(G,dtype=tf.float32))

#### Tensorflow vs numpy

In [ ]:
npArr=tf.constant(np.array([34,54,2,5,3]))
npArr

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([34, 54,  2,  5,  3])>

In [ ]:
# Convert tensor to a numpy array
np.array(npArr),type(np.array(npArr))

(array([34, 54,  2,  5,  3]), numpy.ndarray)

In [ ]:
#Alternative for converting in numpy array
npArr.numpy(),type(npArr.numpy())

(array([34, 54,  2,  5,  3]), numpy.ndarray)

In [ ]:
# The default datatype of numpy array and tensor is different. keep it in mind!
A = tf.constant([33,543,53,343])
B=np.array([3,243,332,543])
A.dtype,B.dtype

(tf.int32, dtype('int64'))